title: Wecide
description: Wecide helps a group of people pick a film to watch together.
author: Carolina Campos
email: gr.camposr@gmail.com
theme: jekyll-theme-primer # A standard GitHub Pages supported theme
url: "https://<your-username>.github.io" # Replace with your GitHub Pages URL
baseurl: "/wecide" # Replace with your repository name if applicable

# Build settings
markdown: kramdown
include:
  - wecide-privacy-policy.html