title: Wecide
description: Wecide helps a group of people pick a film to watch together.
author: Carolina Campos
theme: jekyll-theme-primer
baseurl: "/wecide"
url: "https://grcamposr.github.io"

# This creates the navigation tabs at the top of your site
header_pages:
  - privacy/index.html
